batch_size: 32
block_size: 768
max_iters: 4000
eval_interval: 300
learning_rate: 2e-4
eval_iters: 200
n_embed: 522
n_layer: 8
n_head: 6
dropout: 0.2
generated_characters: 2000
model_save_threshold: 1.5

input_file: "input.txt"